# Copyright (c) 2026 Xavier Beheydt <xavier.beheydt@gmail.com>

# Every service repo provides the recipes up, down, start, stop and ps,
# so the parent repo can drive all of them the same way.

# List available recipes
default:
    @just --list

# Create .env from .env.example if it does not exist yet
env:
    @test -f .env || { cp .env.example .env && echo "Created .env from .env.example"; }

# Generate a local CA (kept if present) and a certificate for DOMAIN and *.DOMAIN
certs: env
    #!/usr/bin/env bash
    set -euo pipefail
    set -a; . ./.env; set +a
    : "${DOMAIN:?DOMAIN is required in .env}"
    mkdir -p certs
    cd certs
    if [ ! -f ca.crt ]; then
        openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
            -subj "/CN=Traefik Local CA" \
            -addext "basicConstraints=critical,CA:TRUE" \
            -addext "keyUsage=critical,keyCertSign,cRLSign" \
            -keyout ca.key -out ca.crt
    fi
    openssl req -newkey rsa:2048 -nodes -subj "/CN=${DOMAIN}" \
        -keyout local.key -out local.csr
    openssl x509 -req -in local.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
        -days 397 -out local.crt -extfile <(printf '%s\n' \
            "subjectAltName=DNS:${DOMAIN},DNS:*.${DOMAIN}" \
            "basicConstraints=CA:FALSE" \
            "keyUsage=critical,digitalSignature,keyEncipherment" \
            "extendedKeyUsage=serverAuth")
    rm local.csr
    chmod 600 ca.key local.key
    cat > tls.yml <<'YAML'
    # Generated by `just certs`: default certificate for local testing
    tls:
      stores:
        default:
          defaultCertificate:
            certFile: /certs/local.crt
            keyFile: /certs/local.key
    YAML
    echo "Certificate for ${DOMAIN} and *.${DOMAIN} written to certs/"
    echo "Trust certs/ca.crt in your browser, or use: curl --cacert certs/ca.crt"

# Create the shared internal proxy network if it is missing
networks:
    #!/usr/bin/env bash
    set -euo pipefail
    if ! internal=$(docker network inspect -f '{{{{.Internal}}' proxy 2>/dev/null); then
        docker network create --internal proxy >/dev/null
        echo "Created the internal proxy network"
    elif [ "$internal" != true ]; then
        echo "The proxy network is not internal: stop every stack, run \`docker network rm proxy\`, then start them again" >&2
        exit 1
    fi

# Start the stack (creates .env, the proxy network, and the local certificate when no resolver is set)
up: env networks
    #!/usr/bin/env bash
    set -euo pipefail
    set -a; . ./.env; set +a
    if [ -z "${TLS_CERT_RESOLVER:-}" ] && [ ! -f certs/local.crt ]; then
        {{ just_executable() }} certs
    fi
    docker compose up -d

# Stop and remove the containers (the letsencrypt volume is kept)
down:
    docker compose down

# Start the existing containers
start:
    docker compose start

# Stop the containers without removing them
stop:
    docker compose stop

# Show the containers of the stack
ps:
    docker compose ps

# Follow the logs
logs:
    docker compose logs -f

# Remove the containers, the letsencrypt volume, .env and certs/ (the shared proxy network is kept)
[confirm("Remove containers, letsencrypt volume, .env and certs/? [y/N]")]
clean: env
    docker compose down --volumes --remove-orphans
    rm -f .env certs/*
